name: BBC News

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          sudo apt-get install ncal
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Set current date in env variables
        run: |
          echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Fetch news
        run: |
          mkdir -p output
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)
          SERIES_INDEX="${YEAR}${MONTH}.${DAY}"

          ebook-convert "custom-recipes/BBC News.recipe" "bbc-news-${{ env.DATE }}.kepub" \
            --recipe-specific-option=days:1 \
            --authors "Various Authors" \
            --author-sort "Various Authors" \
            --tags "News" \
            --publisher "BBC" \
            --series "BBC News" \
            --series-index "$SERIES_INDEX"

      - name: Upload .kepub file to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bbc-news-${{ env.DATE }}
          path: bbc-news-${{ env.DATE }}.kepub
          retention-days: 90

      - name: Upload .kepub file to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: bbc-news-${{ env.DATE }}.kepub
          target: ${{ secrets.VPS_PATH }}
