name: Foreign Affairs

on:
  schedule:
    - cron: "0 0 1 */2 *"
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Fetch news
        run: |
          mkdir -p output
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          SERIES_INDEX="${YEAR}.${MONTH}"

          ebook-convert "Foreign Affairs.recipe" "output/foreign-affairs.kepub" \
            --authors "Various Authors" \
            --author-sort "Various Authors" \
            --tags "News" \
            --publisher "Foreign Affairs" \
            --series "Foreign Affairs" \
            --series-index "$SERIES_INDEX"

      - name: Upload .kepub file to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: foreign-affairs-kepub
          path: output/foreign-affairs.kepub
          retention-days: 90
